name: Docker Build

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release version tag"
        required: true

jobs:      
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Checkout aq2-tng
        uses: actions/checkout@v3
        with:
          repository: actionquake/aq2-tng
          path: aq2-tng
          ref: aqtion

      - name: Checkout q2pro
        uses: actions/checkout@v3
        with:
          repository: actionquake/q2pro
          path: q2pro
          ref: aqtion

      - name: Checkout q2admin
        uses: actions/checkout@v3
        with:
          repository: actionquake/q2admin
          path: q2admin
          ref: aqtion

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        run: |
          docker build -t aqtiongame/server:${{ github.event.inputs.release_tag }} .
          docker push aqtiongame/server:${{ github.event.inputs.release_tag }}